
services:
  jenkins:
    image: my-jenkins-image:june-20
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jdk_data:/var/jenkins_home/tools/hudson.model.JDK
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '1001'   # host docker group GID (replace with the id on your device)
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-data:
    external: true
  jdk_data:
    external: true

networks:
  jenkins:
    name: jenkins
    driver: bridge
