
services:
  jenkins:
    image: myjenkins-blueocean:lts-jdk17
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jdk_data:/var/jenkins_home/tools/hudson.model.JDK
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 1001   # host docker group GID
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-data:
  jdk_data:

networks:
  jenkins:
    driver: bridge
