name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      tests:
        description: 'Name of the test class to run (e.g., MyClassName)'
        required: false
        default: ''
      tests_suite:
        description: 'Path to the TestNG suite XML file (e.g., path/to/your_testng.xml)'
        required: false
        default: ''
      browser:
        description: 'Browser to use for tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BROWSER: ${{ github.event.inputs.browser }}
      TESTS: ${{ github.event.inputs.tests }}
      TESTS_SUITE: ${{ github.event.inputs.tests_suite }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Tests
        run: |
          if [ "$TESTS" != "" ]; then
            mvn clean -Dtest=$TESTS -Dbrowser=$BROWSER test
          elif [ "TESTS_SUITE" != "" ]; then
            mvn clean test -DsuiteXmlFile=TESTS_SUITE -Dbrowser=$BROWSER
          else
            mvn clean test
          fi

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          echo "/usr/share/allure/bin" >> $GITHUB_ENV

      - name: Generate Allure Report
        run: allure generate --single-file target/allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-tests-report
          path: allure-report